export const LAYOUTITEMS_REQUEST = 'LAYOUTITEMS_REQUEST';
export const SET_LAYOUTITEMS = 'SET_LAYOUTITEMS';
export const FETCH_LAYOUTITEMS_FAILED = 'FETCH_LAYOUTITEMS_FAILED';

export const ABOUT_PAGE_REQUEST = 'ABOUT_PAGE_REQUEST';
export const SET_ABOUT_PAGE = 'SET_ABOUT_PAGE';
export const FETCH_ABOUT_PAGE_FAILED = 'FETCH_ABOUT_PAGE_FAILED';



