export const SET_LAYOUTITEMS = 'SET_LAYOUTITEMS';
export const FETCH_LAYOUTITEMS_FAILED = 'FETCH_LAYOUTITEMS_FAILED';


export const SEARCH_REQUEST= 'SEARCH_REQUEST';
export const SEARCH_SUCCESS= 'SEARCH_SUCCESS';
export const SEARCH_ERROR= 'SEARCH_ERROR';
export const RANDOM_CARD_REQUEST= 'RANDOM_CARD_REQUEST';
export const RANDOM_CARD_SUCCESS= 'RANDOM_CARD_SUCCESS';
export const RANDOM_CARD_ERROR= 'RANDOM_CARD_ERROR';
export const CARD_DETAILS_REQUEST= 'CARD_DETAILS_REQUEST';
export const CARD_DETAILS_SUCCESS='CARD_DETAILS_SUCCESS';
export const CARD_DETAILS_ERROR= 'CARD_DETAILS_ERROR';


